kind: Namespace
apiVersion: v1
metadata:
  name: data-export
  labels:
    name: data-export
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: data-export
  namespace: data-export
spec:
  components:
    - name: publish-export-data
      type: edge-worker
      properties:
        runtime:
          - publish-export-data
        image: ci4rail/publish-export-data:latest
        name: publish-export-data
      traits:
        - type: edge-network-participant
          properties:
            networks:
              - data-export-network
    - type: application-network
      name: data-export-network
      properties:
        subjects:
          - name: data-export-subjects
            subjects:
              - EXPORT.>
            stream: data-export-stream
        streams:
          - name: data-export-stream
            location: node
            config:
              storage: file
              retention: limits
              maxMsgsPerSubject: -1
              maxMsgs: -1
              maxBytes: 1073741824
              maxAge: 10d
              maxMsgSize: -1
              discard: old
          - name: data-export-stream-aggregate
            location: main
            link:
              stream: data-export-stream
            config:
              storage: file
              retention: limits
              maxMsgsPerSubject: -1
              maxMsgs: -1
              maxBytes: 6442450944
              maxAge: 10d
              maxMsgSize: -1
              discard: old
