apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mount
  namespace: mount
spec:
  components:
    - name: rw-files
      type: edge-worker
      properties:
        runtime:
          - mount
        image: ghcr.io/edgefarm/example-mount:pr-6
        name: rw-files
      traits:
        - type: volumes
          properties:
            volumes:
              - name: mount-name
                type: hostPath
                path: /data/path-on-host/
                mountPath: /path-in-container
                mountType: DirectoryOrCreate
                readOnly: false
