apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: data-export
spec:
  components:
    - name: publish-export-data
      type: edge-worker
      properties:
        runtime:
          - publish-export-data
        image: ci4rail/publish-export-data:latest
        name: publish-export-data
      traits:
        - type: edge-network-participant
          properties:
            networks:
              - data-export-network

