apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: data-export-network
spec:
  components:
    - type: application-network
      name: data-export-network
      properties:
        subjects:
          - name: data-export-subjects
            subjects:
              - export.>
            stream: data-export-stream
        streams:
          - name: data-export-stream
            location: node
            config:
              storage: file
              retention: limits
              maxMsgsPerSubject: -1
              maxMsgs: -1
              maxBytes: 1073741824
              maxAge: 10d
              maxMsgSize: -1
              discard: old
          - name: data-export-stream-aggregate
            location: main
            link:
              stream: data-export-stream
            config:
              storage: file
              retention: limits
              maxMsgsPerSubject: -1
              maxMsgs: -1
              maxBytes: 6442450944
              maxAge: 10d
              maxMsgSize: -1
              discard: old
